/************************************************************************
*
* CppSharp
* Licensed under the MIT license.
*
************************************************************************/

#pragma once

#include "Helpers.h"
//#include "Sources.h"
#include <algorithm>

struct ISourceLocation;
enum TypeKind;
enum ArraySize;
enum CallingConvention;
enum ExceptionSpecType;
enum TypeModifier;
enum ArgumentKind;
enum PrimitiveType;
enum CppAbi;
enum VTableComponentKind;
enum DeclarationKind;
enum AccessSpecifier;
enum StatementClass;
enum CXXMethodKind;
enum CXXOperatorKind;
enum FriendKind;
enum RefQualifierKind;
enum EnumModifiers;
enum TemplateSpecializationKind;
enum MacroLocation;
enum ArchType;
enum DocumentationCommentKind;
enum ParamCommandComment_PassDirection;
enum InlineCommandComment_RenderKind;
enum CommentKind;
struct IType;
struct IQualifiedType;
struct ITagType;
struct IArrayType;
struct IFunctionType;
struct IPointerType;
struct IMemberPointerType;
struct ITypedefType;
struct IAttributedType;
struct IDecayedType;
struct ITemplateArgument;
struct ITemplateSpecializationType;
struct IDependentTemplateSpecializationType;
struct ITemplateParameterType;
struct ITemplateParameterSubstitutionType;
struct IInjectedClassNameType;
struct IDependentNameType;
struct IPackExpansionType;
struct IUnaryTransformType;
struct IVectorType;
struct IBuiltinType;
struct IVTableComponent;
struct IVTableLayout;
struct IVFTableInfo;
struct ILayoutField;
struct ILayoutBase;
struct IClassLayout;
struct IDeclaration;
struct IDeclarationContext;
struct ITypedefNameDecl;
struct ITypedefDecl;
struct ITypeAlias;
struct IFriend;
struct IStatement;
struct IExpression;
struct IBinaryOperator;
struct ICallExpr;
struct ICXXConstructExpr;
struct IInitListExpr;
struct ISubStmtExpr;
struct IParameter;
struct IFunction;
struct IMethod;
struct IEnumeration;
struct IEnumeration_Item;
struct IVariable;
struct IBaseClassSpecifier;
struct IField;
struct IAccessSpecifierDecl;
struct IClass;
struct ITemplate;
struct ITypeAliasTemplate;
struct ITemplateParameter;
struct ITemplateTemplateParameter;
struct ITypeTemplateParameter;
struct INonTypeTemplateParameter;
struct IClassTemplate;
struct IClassTemplateSpecialization;
struct IClassTemplatePartialSpecialization;
struct IFunctionTemplate;
struct IFunctionTemplateSpecialization;
struct IVarTemplate;
struct IVarTemplateSpecialization;
struct IVarTemplatePartialSpecialization;
struct INamespace;
struct IPreprocessedEntity;
struct IMacroDefinition;
struct IMacroExpansion;
struct ITranslationUnit;
struct INativeLibrary;
struct IASTContext;
struct IComment;
struct IBlockContentComment;
struct IBlockContentComment;
struct IFullComment;
struct IInlineContentComment;
struct IInlineContentComment;
struct IParagraphComment;
struct IBlockCommandComment_Argument;
struct IBlockCommandComment;
struct IBlockCommandComment;
struct IParamCommandComment;
struct ITParamCommandComment;
struct IVerbatimBlockLineComment;
struct IVerbatimBlockComment;
struct IVerbatimLineComment;
struct IInlineCommandComment_Argument;
struct IInlineCommandComment;
struct IHTMLTagComment;
struct IHTMLTagComment;
struct IHTMLStartTagComment_Attribute;
struct IHTMLStartTagComment;
struct IHTMLEndTagComment;
struct ITextComment;
struct IRawComment;
